version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: destify_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: destify_user
      POSTGRES_PASSWORD: destify_pass
      POSTGRES_DB: destify_movie
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./DestifyMovie.API/Dockerfile
    container_name: destify_api
    restart: always
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=destify_movie;Username=destify_user;Password=destify_pass"
    depends_on:
      - postgres

volumes:
  postgres_data:
