name: .NET CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configuração do .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    # Restaurar dependências
    - name: Restore Dependencies
      run: dotnet restore

    # Build do projeto
    - name: Build Solution
      run: dotnet build --no-restore --configuration Release

    # Executar os testes
    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal --configuration Release
